config/routes.rb
Rails.application.routes.draw do
  
  resources :subcategories
  resources :categories
  resources :products
  
  root 'page#index'

  get 'page/about'

  get 'page/contact'

end

app/models/category.rb
class Category < ActiveRecord::Base
	# define table
	self.table_name = "products_category"

	# define relationships
	has_many :subcategories, :foreign_key => "parent_id", :dependent => :destroy
	has_many :products

	#validation rules
	validates_presence_of	:name

	def self.list
		where(:parent_id => nil)
	end
	
end

app/models/product.rb
class Product < ActiveRecord::Base

	#define relationships
	belongs_to :category
	belongs_to :subcategory

	# validates attribute values are not empty
	validates_presence_of	:name, :description, :price
	#validates attribute values maximum length
	validates_length_of 	:name, maximum: 50
	validates_length_of 	:description, maximum: 250
	#validates attribute is a currency
	validates 				:price, numericality: {greater_than_or_equal_to: 0.01}
	#validates attribute is a boolean and default is true
	#validates 				:is_active, inclusion: { in: [true, false]}

end

app/models/subcategory.rb
class Subcategory < Category

	belongs_to :category, :foreign_key => "parent_id"

	def self.list(catid)
		where("parent_id = ?", catid) if catid.present?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.list
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.where(parent_id: nil)
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @categories = Category.where(parent_id: nil)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
	before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

	def index
		@subcategories = Subcategory.all
	end

	def new
		@subcategory = Subcategory.new
	end

	def edit
	end

	def create
		@subcategory = Subcategory.new(subcategory_params)

		respond_to do |format|
			if @subcategory.save
			  format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@subcategory.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_subcategory
			@subcategory = Subcategory.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def subcategory_params
			params.require(:subcategory).permit(:name, :parent_id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", :required => 'required' %>
    </div>
  </fieldset>

  <div class="actions">
    <%= f.submit class: "btn btn-primary", data: { confirm: 'Are you sure you want to create this category as a parent category?' } %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<div class="text-right">
  <%= link_to icon('plus-circle', 'New Category'), new_category_path, class: "btn btn-primary" %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.parent_id == 0? "Top Level" : category.parent_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="This is an example of an ecommerce store built on Ruby on Rails.">
  <title>SampleStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Static navbar -->
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="top-header row">
      </div>
      <div class="middle-header row">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Sample Store</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li class="btn btn-primary cart-btn"><a href="#"><i class="fa fa-shopping-cart"></i>Cart</a></li>
        </ul>
      </div>
      <div class="bottom-header row">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><%= link_to "Store", products_path %></li>
            <li><%= link_to "Who We Are", page_about_path %></li>
            <li><%= link_to "Contact Us", page_contact_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </nav>

  <div class="container">

    <% if notice %>
    <div class="row">
      <p class="alert alert-success"><strong><%= notice %></strong></p>
    </div>
    <% end %>
  
    <%= yield %>
  
  </div>

</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Product name", :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :description, class: "control-label" %>
      <%= f.text_area :description, class: "form-control", placeholder: "Product description", :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :price, class: "control-label" %>
      <div class="input-group">
        <div class="input-group-addon">$</div>
        <%= f.text_field :price, class: "form-control", placeholder: "0.00", :required => 'required' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :category_id, class: "control-label" %>
      <%= f.select :category_id, options_from_collection_for_select(@categories, :id, :name), {:prompt => "Choose a category"}, {class: "form-control", :required => true} %>
    </div>
  </fieldset>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing Products</h1>

<div class="text-right">
  <%= link_to icon('plus-circle', 'New Product'), new_product_path, class: "btn btn-primary" %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th class="text-center">Price</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= truncate(product.description, lenght: 100, omission: '...') %></td>
        <td class="text-center"><%= number_to_currency(product.price) %></td>
        <td><%= link_to icon('list-alt', "Show"), product, title: "Show product" %></td>
        <td><%= link_to icon('edit', "Edit"), edit_product_path(product), title: "Edit product" %></td>
        <td><%= link_to icon('trash-o', "Delete"), product, method: :delete, data: { confirm: 'Are you sure you want to delete this product?' }, title: "Delete product" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<div class="col-md-6">

	<%= render 'form' %>

	<%= link_to 'Back', products_path %>
	
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>Name: <%= @product.name %></p>
<p>Description: <%= @product.description %></p>
<p>Price: <%= number_to_currency(@product.price) %></p>
<p></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/subcategories/edit.html.erb
edit.html.erb

app/views/subcategories/index.html.erb
<h1>Listing Subcategories</h1>

<div class="text-right">
  <%= link_to icon('plus-circle', 'New Subcategory'), new_subcategory_path, class: "btn btn-primary" %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @subcategories.present? %>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.category %></td>
        <td><%= link_to 'Show', subcategory %></td>
        <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% else %>
      <tr>
      <td colspan="5">There are no subcategories set yet.</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/subcategories/new.html.erb
new.html.erb

app/views/subcategories/show.html.erb
show.html.erb